require 'omniship/usps/return_label/customer'
require 'omniship/usps/return_label/permit'
require 'omniship/usps/return_label/pdu'
require 'omniship/usps/return_label/retailer'
require 'omniship/usps/return_label/request'
require 'omniship/usps/return_label/response'
